import type { NextPage } from "next";
import Head from "next/head";
import Controls from "../components/Controls";
import Display from "../components/Display";
import styles from "../styles/Home.module.css";
import { CounterContext } from "../utils/CounterContext";
import { useContext } from "react";

const Home: NextPage = () => {

  const {state, dispatch}  = useContext(CounterContext)

  return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Display {...state} />
        <Controls dispatch={dispatch} />
      </div>
  );
};

export default Home;
